### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by lnmunhoz** [react-theming/create-mui-theme#1]
Hi, we want to use your project but the API hosted on graph.cool seems to have some issue.
The api is open source as well? I couldn't find it anywhere in your organization repos.

This is the error returning from the call
```
{
  "data": {
    "createTheme": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createTheme"
      ],
      "code": 5008,
      "message": "empty.last",
      "requestId": "eu-west-1:simple:ck07slfhq05nt0159kth24prb"
    }
  ]
}
```

Thank you so much!

**Comment by usulpro** [comment]
Hey @lnmunhoz 

Looks like it was a problem with Graphcool service. I've seen it as well this morning.
But at this moment it starts to work again

So looks like I can close it.
Let me please know if this problem come again

**Comment by lnmunhoz** [comment]
Hey @UsulPro , all right, thank you! 
By any chance can you open source the api hosted on graph.cool if possible?
